# This is a basic workflow to help you get started with Actions

name: tweet

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 11,16 * * *" #runs at 11:00 and 16:00 UTC everyday
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: install dependencies
        run: pip install -r requirements.txt
        
      - name: execute py script # run the run.py to get the latest data
        run: |
          python scripts/post.py
        env:
          api_key: ${{ secrets.API_KEY }}
          api_key_secret: ${{ secrets.API_KEY_SECRET }}
          bearer_token: ${{ secrets.BEARER_TOKEN }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          access_token_dog: ${{ secrets.ACCESS_TOKEN_DOG }}
          access_token_cat: ${{ secrets.ACCESS_TOKEN_CAT }}
          access_token_secret_dog: ${{ secrets.ACCESS_TOKEN_SECRET_DOG }}
          access_token_secret_cat: ${{ secrets.ACCESS_TOKEN_SECRET_CAT }}
